/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ModelStats {
  'confidenceLevel' : string,
  'recentAccuracy' : number,
  'calibration' : number,
}
export interface RaceEntry {
  'followedRecommendation' : boolean,
  'odds' : Array<number>,
  'betSize' : bigint,
  'modelPrediction' : bigint,
  'timestamp' : Time,
  'outcome' : [] | [RaceOutcome],
}
export interface RaceOutcome {
  'thirdPlace' : bigint,
  'winner' : bigint,
  'secondPlace' : bigint,
}
export interface Settings {
  'autoBetSizing' : boolean,
  'sessionOnlyMode' : boolean,
  'doNotBetMode' : boolean,
  'recentFormWindow' : bigint,
  'strategyMode' : string,
  'recencyWeighting' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'getModelStats' : ActorMethod<[], [] | [ModelStats]>,
  'getRaceHistory' : ActorMethod<[], Array<RaceEntry>>,
  'getUserSettings' : ActorMethod<[], [] | [Settings]>,
  'logRaceEntry' : ActorMethod<
    [Array<number>, bigint, bigint, boolean],
    undefined
  >,
  'resetData' : ActorMethod<[], undefined>,
  'updateModelStats' : ActorMethod<[ModelStats], undefined>,
  'updateRaceOutcome' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateUserSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];