/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ModelStats = IDL.Record({
  'confidenceLevel' : IDL.Text,
  'recentAccuracy' : IDL.Float64,
  'calibration' : IDL.Float64,
});
export const Time = IDL.Int;
export const RaceOutcome = IDL.Record({
  'thirdPlace' : IDL.Nat,
  'winner' : IDL.Nat,
  'secondPlace' : IDL.Nat,
});
export const RaceEntry = IDL.Record({
  'followedRecommendation' : IDL.Bool,
  'odds' : IDL.Vec(IDL.Float64),
  'betSize' : IDL.Nat,
  'modelPrediction' : IDL.Nat,
  'timestamp' : Time,
  'outcome' : IDL.Opt(RaceOutcome),
});
export const Settings = IDL.Record({
  'autoBetSizing' : IDL.Bool,
  'sessionOnlyMode' : IDL.Bool,
  'doNotBetMode' : IDL.Bool,
  'recentFormWindow' : IDL.Nat,
  'strategyMode' : IDL.Text,
  'recencyWeighting' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getModelStats' : IDL.Func([], [IDL.Opt(ModelStats)], ['query']),
  'getRaceHistory' : IDL.Func([], [IDL.Vec(RaceEntry)], ['query']),
  'getUserSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
  'logRaceEntry' : IDL.Func(
      [IDL.Vec(IDL.Float64), IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'resetData' : IDL.Func([], [], []),
  'updateModelStats' : IDL.Func([ModelStats], [], []),
  'updateRaceOutcome' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateUserSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ModelStats = IDL.Record({
    'confidenceLevel' : IDL.Text,
    'recentAccuracy' : IDL.Float64,
    'calibration' : IDL.Float64,
  });
  const Time = IDL.Int;
  const RaceOutcome = IDL.Record({
    'thirdPlace' : IDL.Nat,
    'winner' : IDL.Nat,
    'secondPlace' : IDL.Nat,
  });
  const RaceEntry = IDL.Record({
    'followedRecommendation' : IDL.Bool,
    'odds' : IDL.Vec(IDL.Float64),
    'betSize' : IDL.Nat,
    'modelPrediction' : IDL.Nat,
    'timestamp' : Time,
    'outcome' : IDL.Opt(RaceOutcome),
  });
  const Settings = IDL.Record({
    'autoBetSizing' : IDL.Bool,
    'sessionOnlyMode' : IDL.Bool,
    'doNotBetMode' : IDL.Bool,
    'recentFormWindow' : IDL.Nat,
    'strategyMode' : IDL.Text,
    'recencyWeighting' : IDL.Float64,
  });
  
  return IDL.Service({
    'getModelStats' : IDL.Func([], [IDL.Opt(ModelStats)], ['query']),
    'getRaceHistory' : IDL.Func([], [IDL.Vec(RaceEntry)], ['query']),
    'getUserSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
    'logRaceEntry' : IDL.Func(
        [IDL.Vec(IDL.Float64), IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'resetData' : IDL.Func([], [], []),
    'updateModelStats' : IDL.Func([ModelStats], [], []),
    'updateRaceOutcome' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateUserSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };